# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
schedules:
- cron: "*/15 * * * *"
  branches:
    include:
    - main
  always: true
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      filePath: getGroups.ps1
      #arguments: $(username) $(password)
  - task: CopyFiles@2
    inputs:
      Contents: '*.log'
      targetfolder: $(Build.ArtifactstagingDirectory)
       echo $(Build.ArtifactstagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactstagingDirectory)
      artifactName: output.log