# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
schedules:
- cron: "*/15 * * * *"
  branches:
    include:
    - main
  always: true
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
  - task: Grunt@0
    inputs:
      gruntFile: 'getGroups.js'
      targets: 
      gruntCli: 'node_modules/grunt-cli/bin/grunt'